### PR TITLE
Resolves #138

### LINKED ISSUE #138: Opportunity panel
Create a panel to show as boxplots the several opportunity observations:
 - Digitalization;
 - Notification;
 - Result;
 - Terapy;
 - ...

I'm working on the dataset extraction and database update.
I couldn't find any example of boxplots with C3.js D3-based graphs.
The goal is the plotly style, if possible:
https://plot.ly/python/box-plots/

### PR DESCRIPTION
**Pull request by xmnlab**
@marfcg 

the boxplot is in the panel.

i need to fix some style issue .. but you can see the result and ask me any change ...

### CODE REVIEW

**Comment by marfcg** [comment]
Both new panels (etiological time series and oppotunity boxplots) are not showing the data specific to the selected UF or regional area.
It is always showing the data for the whole country in those cases.
When region is selected ("região geopolitica"), then it correctly shows the data for the region selected on the map.

That aside, they are looking very nice.

**Comment by xmnlab** [comment]
ok .. I will take a look. thanks :+1:

**Comment by xmnlab** [comment]
@marfcg 

can you review if the problem was fixed?

**Comment by marfcg** [comment]
Doing some checks here, it seems that the problem is with specific UFs. For instance, if Paraná, Bahia or Amazonas is selected, it shows just fine.
But if Rio Grande do Sul, Santa Catarina or Minas Gerais is selected, it keeps the data from the previous UF.

Also, when unselecting any UF, it does not go back to Brazil's data. Weird...

PS: I've checked with the "Resumido" view only, for now.

**Comment by xmnlab** [comment]
maybe white space problem.

**Comment by xmnlab** [comment]
@marfcg 

can you check it again?

**Comment by marfcg** [comment]
It's working! I might have failed to reinstall after pulling the PR :/

**Pull request closed without merging**
