### PR TITLE
First version using postgresql

### PR DESCRIPTION
**Pull request by xmnlab**
@marfcg 

I had made some changes in the data-migration notebook ... 

to test this new version .. you will need a postgresql instance and you will need a user and password to make the connection.

in the same folder of the `settings.py` file, you will need to create the `local_settings.py` file with this structure:

```py
from .settings import *

DEBUG = True
UPDATE_DATA = False

DATABASE = {
    'NAME': 'fludashboard_database_name',  # set your database name
    'USER': 'fludashboard_user', # set your user name
    'PASSWORD': 'fludashboard_password',  # set your password
    'HOST': 'localhost',
    'PORT': '5432',
}
```

After this create configuration you can run the notebook and it should creates the tables and imports the data.

Next I will create a dockerfile for the database system with the migration process.

### CODE REVIEW

**Comment by marfcg** [comment]
@xmnlab which YAML package for the corresponding python module are you using?

**Comment by xmnlab** [comment]
@marfcg 

sorry .. I forgot to add the package to requirements ... 

the package is PyYAML

**Comment by marfcg** [comment]
Noob question...
So, I have created the local_settings.py with my local config.
How do I get the system to use that instead of the database config from settings.py?

**Comment by xmnlab** [comment]
@marfcg 

this is not a noob question .. actually this new version (with yaml config file) doesn't use local_settings any more .. just ~/.flu.yaml ... 

this file is created automatically if doesn't exist.

**Comment by marfcg** [comment]
So, I've edited my local .flu.yaml, the YAML.ipynb recognizes it just fine, but the Dataset-Migration still does not read the right config...
```
OperationalError: (psycopg2.OperationalError) could not translate host name "<DATABASE_HOST_HERE>" to address: Name or service not known
```

**Comment by xmnlab** [comment]
you are totally right .. I will fix it now! thanks!

**Comment by xmnlab** [comment]
@marfcg 

Actually, I am testing here and it is working fine ...

I added 2 missing parameters to YAML notebook (APP_HOST and APP_PORT)

**Comment by marfcg** [comment]
Hmmm... when running python -m fludashboard.app, I'm getting a server error with the following traceback:

```
Traceback (most recent call last):
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: syntax error at or near ","
LINE 2:         SELECT , territory.name AS territory_name
                       ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/fludashboard-0.3.2-py3.6.egg/fludashboard/libs/views.py", line 58, in index
    dataset_id=1, scale_id=1, territory_id=0
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/fludashboard-0.3.2-py3.6.egg/fludashboard/libs/flu_data.py", line 299, in read_data
    return pd.read_sql(sql % sql_param, conn)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/io/sql.py", line 416, in read_sql
    chunksize=chunksize)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/io/sql.py", line 1092, in read_query
    result = self.execute(*args)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/pandas/io/sql.py", line 983, in execute
    return self.connectable.execute(*args, **kwargs)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/marfcg/miniconda3/envs/fludashboard-development/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near ","
LINE 2:         SELECT , territory.name AS territory_name
                       ^
 [SQL: '\n        SELECT , territory.name AS territory_name\n        FROM historical_estimated_values \n          INNER JOIN territory\n            ON (historical_estimated_values.territory_id = territory.id)\n        WHERE dataset_id=1 \n          AND scale_id=1\n         AND territory_id=0']
127.0.0.1 - - [21/Nov/2017 20:55:53] "GET / HTTP/1.1" 500 -
```

**Comment by marfcg** [comment]
As you mentioned, when running the notebook, it gets the wrong settings config.
When running the app, it gets the correct one, but throws me the error above.

PS: this was before https://github.com/FluVigilanciaBR/fludashboard/pull/108/commits/b5b206f3aaab61b963efbc2a509a901fde9ab686

**Comment by xmnlab** [comment]
@marfcg 

I have made new commits .. can you pull these commits there?

to prepare the data structure you will need to execute this:

```sh

python -m fludashboard.libs.migration

```

**Comment by marfcg** [comment]
Working great, @xmnlab !

**Pull request merged**
