### PR TITLE
Package prepared to be packaged with pypi and conda

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by marfcg** [comment]
@xmnlab 
After installing with `python3 setup.py install` and running the module `fludashboard.runwsgi` I'm getting the following:
```
python3 -m fludashboard.runwsgi
[II] Starting update data ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "fludashboard/app.py", line 8
    def update_data_files(update_data: bool):
                                     ^
SyntaxError: invalid syntax
[II] Starting update data [OK]
[II] Starting app ...
```
So I shut down this process and tried running app.py directly, which downloaded the data files into fludashboard/data (this folder used to be on the base folder, not inside the folder where the app script is -- not sure if this is relevant), I'm getting an error that it is not being able to locate the data:
```
marfcg@marfcg-Satellite-L840:~/codes/FluVigilanciaBR/fludashboard/fludashboard$ sudo python3 app.py
[sudo] senha para marfcg: 
cd /storage/Marcelo/codes/FluVigilanciaBR/fludashboard/fludashboard/data  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/clean_data_epiweek-weekly-incidence_w_situation.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/current_estimated_values.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/historical_estimated_values.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-report.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-typical.csv
--2017-10-24 11:40:54--  https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/clean_data_epiweek-weekly-incidence_w_situation.csv
Conectando-se a [LOCAL PROXY OMITTED]... conectado.
A requisição Proxy foi enviada, aguardando resposta... 200 OK
Tamanho: 47442504 (45M) [text/plain]
Salvando em: “clean_data_epiweek-weekly-incidence_w_situation.csv”

clean_data_epiweek- 100%[===================>]  45.24M  7.88MB/s    in 5.7s    

2017-10-24 11:41:02 (7.93 MB/s) - “clean_data_epiweek-weekly-incidence_w_situation.csv” salvo [47442504/47442504]

--2017-10-24 11:41:02--  https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/current_estimated_values.csv
Conectando-se a [LOCAL PROXY OMITTED]... conectado.
A requisição Proxy foi enviada, aguardando resposta... 200 OK
Tamanho: 10136560 (9.7M) [text/plain]
Salvando em: “current_estimated_values.csv”

current_estimated_v 100%[===================>]   9.67M  8.78MB/s    in 1.1s    

2017-10-24 11:41:04 (8.78 MB/s) - “current_estimated_values.csv” salvo [10136560/10136560]

--2017-10-24 11:41:04--  https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/historical_estimated_values.csv
Conectando-se a [LOCAL PROXY OMITTED]... conectado.
A requisição Proxy foi enviada, aguardando resposta... 200 OK
Tamanho: 3053803 (2.9M) [text/plain]
Salvando em: “historical_estimated_values.csv”

historical_estimate 100%[===================>]   2.91M  8.95MB/s    in 0.3s    

2017-10-24 11:41:04 (8.95 MB/s) - “historical_estimated_values.csv” salvo [3053803/3053803]

--2017-10-24 11:41:04--  https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-report.csv
Conectando-se a [LOCAL PROXY OMITTED]... conectado.
A requisição Proxy foi enviada, aguardando resposta... 200 OK
Tamanho: 34216 (33K) [text/plain]
Salvando em: “mem-report.csv”

mem-report.csv      100%[===================>]  33.41K  --.-KB/s    in 0.001s  

2017-10-24 11:41:04 (22.6 MB/s) - “mem-report.csv” salvo [34216/34216]

--2017-10-24 11:41:04--  https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-typical.csv
Conectando-se a [LOCAL PROXY OMITTED]... conectado.
A requisição Proxy foi enviada, aguardando resposta... 200 OK
Tamanho: 912064 (891K) [text/plain]
Salvando em: “mem-typical.csv”

mem-typical.csv     100%[===================>] 890.69K  4.34MB/s    in 0.2s    

2017-10-24 11:41:05 (4.34 MB/s) - “mem-typical.csv” salvo [912064/912064]

[II] DONE!
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
cd /storage/Marcelo/codes/FluVigilanciaBR/fludashboard/fludashboard/data  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/clean_data_epiweek-weekly-incidence_w_situation.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/current_estimated_values.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/historical_estimated_values.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-report.csv  && \ 
     wget -nc https://raw.githubusercontent.com/FluVigilanciaBR/data/master/data/mem-typical.csv
O arquivo “clean_data_epiweek-weekly-incidence_w_situation.csv” já existe, não será baixado.

O arquivo “current_estimated_values.csv” já existe, não será baixado.

O arquivo “historical_estimated_values.csv” já existe, não será baixado.

O arquivo “mem-report.csv” já existe, não será baixado.

O arquivo “mem-typical.csv” já existe, não será baixado.

[II] DONE!
 * Debugger is active!
 * Debugger pin code: 333-620-606
127.0.0.1 - - [24/Oct/2017 11:41:19] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.11.1-py3.5.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/fludashboard-0.3.0-py3.5.egg/fludashboard/libs/views.py", line 54, in index
    df = flu_data.read_data()
  File "/usr/local/lib/python3.5/dist-packages/fludashboard-0.3.0-py3.5.egg/fludashboard/libs/flu_data.py", line 260, in read_data
    os.path.join(path_data, 'current_estimated_values.csv')
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4175)
    
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8440)
    
FileNotFoundError: File b'/usr/local/lib/python3.5/dist-packages/fludashboard-0.3.0-py3.5.egg/fludashboard/data/current_estimated_values.csv' does not exist
127.0.0.1 - - [24/Oct/2017 11:41:19] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Oct/2017 11:41:19] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Oct/2017 11:41:19] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Oct/2017 11:41:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [24/Oct/2017 11:41:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

A few questions:
- When running the module fludashboard.runwsgi, should it launch the app at 0.0.0.0:5000 or there is something else I'm missing?
- After these changes, what is the correct way to download, install, and run the app at the host?

**Comment by marfcg** [comment]
Side note, related to Docker deployment, on an issue from conda's side:
When trying to deploy the docker (inside PyCharm), I'm getting the following error after step 12:
```
Fetching package metadata ...

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/linux-64/repodata.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f865f5588d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
```

This is related to the following issue:
https://github.com/conda/conda/issues/4738

**Comment by marfcg** [comment]
Update:
When running app.py inside installed package directory, it works fine:
`/usr/local/lib/python3.5/dist-packages/fludashboard-0.3.0-py3.5.egg/fludashboard$ sudo python3 app.py`

**Comment by xmnlab** [comment]
@marfcg 

I think you should install using virtualenv or miniconda .. 

maybe this occur because some permissions problem ...

btw, by default, it is better don't use directly the python of the operation system.

Using miniconda is preferible, because it is a better reproducible way.

**Comment by xmnlab** [comment]
@marfcg 

Ok I will try using `conda config --set ssl_verify no`

thanks!

**Comment by xmnlab** [comment]
@marfcg 

ah sorry .. the dockerfile is just to use after we have the package on pypi and conda-forge repos ..

**Comment by xmnlab** [comment]
@marfcg 

about the new changes:
 
to run the app on development environment you can type*:

```sh
python -m fludashboard.app
```

* to install as a develop package: `python setup.py develop`

this will start the app and download the data files just if the files is not in the folder.

if you want to update the files you can delete the files and start up the app again.

to run the app on production environment you can type:

```sh
python -m fludashboard.runwsgi

```

**Comment by marfcg** [comment]
Please bear with me...
So, I've tried to create a conda env using requirements-dev.txt, to install fludashboard-dev, and got an error at the shell requirement:

```
marfcg@marfcg-Satellite-L840:~/codes/FluVigilanciaBR/fludashboard$ conda env create -f requirements-dev.txt -n fludashboard-dev
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/marfcg/miniconda3  (writable)
    default environment : /home/marfcg/miniconda3
       envs directories : /home/marfcg/miniconda3/envs
                          /home/marfcg/.conda/envs
          package cache : /home/marfcg/miniconda3/pkgs
                          /home/marfcg/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/marfcg/.condarc
             netrc file : /home/marfcg/.netrc
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/marfcg/miniconda3/bin/conda-env create -f requirements-dev.txt -n fludashboard-dev`




    Traceback (most recent call last):
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 56, in get_single_node
        if not self.check_event(StreamEndEvent):
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 116, in check_event
        self.current_event = self.state()
      File "/home/marfcg/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 194, in parse_document_start
        self.peek_token().start_mark)
    ruamel_yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
      in "<unicode string>", line 7, column 1:
        sh
        ^
```

Setting up an env with requirements.txt went ok, though. Once that was done, I was able to install the dev package with `python setup.py develop` and `python -m fludashboard.app` worked well.

```
conda env create -f requirements.txt -n fludashboard
Fetching package metadata .............
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::python-3.6.2-0, conda-forge::zlib-1.2.11-0
  - conda-forge::python-3.6.3-0, conda-forge::zlib-1.2.8-3
libgfortran-3. 100% |####################################################################################| Time: 0:00:00   1.33 MB/s
ncurses-5.9-10 100% |####################################################################################| Time: 0:00:01 789.72 kB/s
sqlite-3.13.0- 100% |####################################################################################| Time: 0:00:05 892.90 kB/s
tk-8.5.19-2.ta 100% |####################################################################################| Time: 0:00:02 764.23 kB/s
openblas-0.2.1 100% |####################################################################################| Time: 0:00:15 945.96 kB/s
readline-6.2-0 100% |####################################################################################| Time: 0:00:00 734.64 kB/s
blas-1.1-openb 100% |####################################################################################| Time: 0:00:00   1.02 MB/s
python-3.6.2-0 100% |####################################################################################| Time: 0:00:21 920.29 kB/s
click-6.7-py36 100% |####################################################################################| Time: 0:00:00 283.32 kB/s
itsdangerous-0 100% |####################################################################################| Time: 0:00:00  51.70 kB/s
markupsafe-1.0 100% |####################################################################################| Time: 0:00:00 237.07 kB/s
numpy-1.13.3-p 100% |####################################################################################| Time: 0:00:10 873.55 kB/s
pytz-2017.2-py 100% |####################################################################################| Time: 0:00:00 668.54 kB/s
unidecode-0.04 100% |####################################################################################| Time: 0:00:00 306.48 kB/s
werkzeug-0.12. 100% |####################################################################################| Time: 0:00:00 690.23 kB/s
python-dateuti 100% |####################################################################################| Time: 0:00:00 835.20 kB/s
gunicorn-19.7. 100% |####################################################################################| Time: 0:00:00 694.61 kB/s
jinja2-2.9.6-p 100% |####################################################################################| Time: 0:00:00 655.94 kB/s
pandas-0.20.3- 100% |####################################################################################| Time: 0:00:26 944.49 kB/s
flask-0.12.2-p 100% |####################################################################################| Time: 0:00:00 196.91 kB/s
#
# To activate this environment, use:
# > source activate fludashboard
#
# To deactivate an active environment, use:
# > source deactivate
#
```
Unfortunately, the production version threw me an error (I've created a separate env fludashboard-production and installed via `python setup.py install`):
```
[II] DONE!
[II] Starting update data [OK]
[II] Starting app ...

Error: Error: '/tmp//fludashboard_error.log' isn't writable [PermissionError(13, 'Permission denied')]
```
Since the development install is running properly, I'll accept this pr and open new issues with those two topics, sounds good?

**Comment by marfcg** [comment]
> Unfortunately, the production version threw me an error (I've created a separate env fludashboard-production and installed via python setup.py install):

To clarify: what didn't work under production install was `python -m fludashboard.runwsgi`. Running  `python -m fludashboard.app` worked fine.

Also, the error I've mentioned in the beginning, related to 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "fludashboard/app.py", line 8
    def update_data_files(update_data: bool):
                                     ^
SyntaxError: invalid syntax
```
Only happens when running the module fludashboard.runwsgi as sudo. When running as normal user, I don't get this error, but I get the permission error regarding the log file.

**Pull request merged**
