### PR TITLE
Age chart and table fixed (fixes #56)

### LINKED ISSUE #56: Age distribution and incidence table on summary panel
On the summary panel, both age distribution and incidence table are showing the info for thelates week alone, not for the season's aggregate.

The notebook has been updated (5c8fd40) with examples of those two informations with the new data structure

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by marfcg** [comment]
I have locally pulled this branch and it seems that the table has been fixed, but not the age dist. chart (i.e., partial fix to #56 ).
Is this correct?

**Comment by xmnlab** [comment]
I didn't make changes in incidence chart (i think ..) just in age/sex chart.

**Comment by xmnlab** [comment]
my test was just based on Pará summary panel.

**Comment by marfcg** [comment]
Yep, it was just about the table and the age chart.
The mention about the incidence chart was my fault. sorry for the confusion.

On my side the age dist. is still showing only the data relative to the latest epiweek available, not the seasonal aggregate. On the table the value seems correct.
Taking Para as our case example (looking only at totals for simplicity):
At week 40:
0-4 ~ 2
10-19 ~ 0.1
60+ ~ 0.2
At week 41:
0-4 ~ 0.125
5-9 ~ 0.125

On the summary panel we see exactly the same age dist as week 41, while the table reports a total incidence of 9.37.

**Pull request merged**
