### PR TITLE
Resolves #151

### LINKED ISSUE #151: Contingency plan alert levels
Per request by the MH, we need to the change the map colors based on the contingency plan instead of what is currently used at the seasonal view mode.
The details and an example is shown in the notebook https://github.com/FluVigilanciaBR/fludashboard/blob/development/Notebooks/Season_color_new_specs.ipynb

Notice that this map will be independent of dataset and scale selected by the user.
It will only depend on the year and territory selected.

To be honest, I would rather create a new view mode called "contingency plan", which would be pretty much identical to the seasonal one. The only changes would be that (1) the map color criteria would follow the rules described on the notebook, and (2) the year will be locked to the latest epiyear in the database. This would be the default view mode upon entering the website.
Therefore, we would have three view modes: weekly ("Detalhado (semana)"), seasonal ("Temporada (ano)"), and contingency plan ("Plano de contingência atual")

This way, we do not lose the information generated for the previous seasons regarding what was the activity level during the seasonal compared to what is expected and we would still provide the info requested by the MH.

### PR DESCRIPTION
**Pull request by xmnlab**
@marfcg 

If you want to see the changes on the layout and controls you can already take a look here.

I am working now on the data manipulation. I want to finish it today.

### CODE REVIEW

**Comment by xmnlab** [comment]
@marfcg 

I create a new column called contingency on the json data.
The operation takes about 6 secs ... I will take a look a way to improve this.

**Comment by marfcg** [comment]
Sorry for the long delay on checking this up. I'm on it now.

**Comment by marfcg** [comment]
@xmnlab 
There seems to be an issue with the table chart.
It is always showing the data for all regions (Nordeste, Norte, Sul, ...) instead of the selected region.

Here goes an example using the "weekly" mode, by UF, with Rio Grande so Sul selected. This is the same for all modes and all aggregation levels.
Notice the "undefined" label on the panel tile as well:
table

**Comment by xmnlab** [comment]
@marfcg 

I will take a look ! thanks!

**Comment by marfcg** [comment]
Regarding time efficiency: I believe the best way to go is for me to incorporate the math behind the contingence level into the data update flow, and throw it into a table inside our data base.
In this way, the fludashboard will only need to read the appropriate table and/or column.

I'll work on that.

**Comment by xmnlab** [comment]
@marfcg 

i think this will be a good improvement :+1:

**Comment by xmnlab** [comment]
@marfcg can you check if that problem with table was fixed?

**Comment by marfcg** [comment]
@xmnlab 
The table issue was solved, but the contingency view button is no longer there.

**Comment by xmnlab** [comment]
that is so weird. can you remove cache and refresh the page on your
browser?

**Comment by marfcg** [comment]
It's working fine. There was some issue with my local branch of your development that I could not pinpoint... I've deleted the local, cloned from your repo and it worked.

**Pull request merged**
