### PR TITLE
incidence curve chart added to prototype

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by marfcg** [comment]
I'm downloading this version locally for testing. I Finally have a decent internet connection.

**Comment by marfcg** [comment]
Unfortunately, I'm having all kinds of problems with conda.... now it does not want to acknowledge my python 3.5.2 installation :/

**Comment by xmnlab** [comment]
:/ do you want some help?

**Comment by marfcg** [comment]
I'll send you an email

---

*Sent from mobile device. My apologies for eventual typos.
Marcelo Ferreira da Costa Gomes
Programa de Computação Científica
Fundação Oswaldo Cruz
PROCC/FIOCRUZ

**Comment by fccoelho** [comment]
@marfcg I managed to run without creating the conda environment.

just do a 

```
sudo pip3 install -r requirements.txt
```

and the app should work. I had issues with conda as well... :-(

**Comment by fccoelho** [comment]
By the way @xmnlab , I don't see an incidence curve when I first open the site. we should pre-select on state or add a message on the empty div saying "Selecione um estado no mapa ao lado."

On other minor detail: the table tile should be "Incidência na semana epidemiológica XX".

Ivan, the interface is much improved! congratulations!

**Comment by fccoelho** [comment]
minor bug.
when the week slider is moved with the arrow keys the visualizations do not update.

**Comment by marfcg** [comment]
@fccoelho: yep, I went this way yesterday night and managed to run it. @xmnlab and I exchanged a few emails to overcome this issue last night.

I have made a few changes to prepare the system for allowing year selection. I couldn't find were the selection takes place, but I changed the basic python codes in /prototype  to receive the year and select the corresponding column from the data file.
Tomorrow I'll have a stable, good connection and I'll share my changes.

Quick update: they simply LOVED it!!!! Congrats, @xmnlab !

**Comment by xmnlab** [comment]
> By the way @xmnlab , I don't see an incidence curve when I first open the
> site. we should pre-select on state or add a message on the empty div
> saying "Selecione um estado no mapa ao lado."

You're right! What should we do?

> On other minor detail: the table tile should be "Incidência na semana
> epidemiológica XX".

OK!

> os valores da tabela mudam por semana mas não quando muda o estado
> selecionado. É para ser assim mesmo @marfcg ?

I think we should write the flow of this app.

> Ivan, the interface is much improved! congratulations!
> Thanks :)

**Comment by xmnlab** [comment]
> I have made a few changes to prepare the system for allowing year
> selection. I couldn't find were the selection takes place, but I changed
> the basic python codes in /prototype to receive the year and select the
> corresponding column from the data file.

Actually, I was focusing just in frontend libraries .. at this point the
all the code looks very ugly yet :(

> Tomorrow I'll have a stable, good connection and I'll share my changes.

Ok, I waiting your change to update my environment.

> Quick update: they simply LOVED it!!!! Congrats,@xmnlab !

Great :) I'm happy about their feedback :)

**Pull request merged**
