### PR TITLE
JS docstring added; unittest added;

### PR DESCRIPTION
**Pull request by xmnlab**
resolved issues:

- Unittest added (issue #53)
- JS docstring added (issue #52)

### CODE REVIEW

**Comment by xmnlab** [comment]
unittest working well in CI environment :)

**Comment by fccoelho** [comment]
One of the tests is failing here:

``` python
fludashboard.app: ERROR: Exception on /data/data-table/2015 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fccoelho/Documentos/Projects_software/fludashboard/fludashboard/app.py", line 211, in data__data_table
    df = group_data_by_season(df, year)
  File "/home/fccoelho/Documentos/Projects_software/fludashboard/fludashboard/srag_data.py", line 49, in group_data_by_season
    df_tmp = df[season_cols].copy()
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2053, in __getitem__
    return self._getitem_array(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2097, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/indexing.py", line 1229, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['0_4_anos' '5_9_anos' '10_19_anos' '20_29_anos' '30_39_anos' '40_49_anos'\n '50_59_anos' '60+_anos'] not in index"
```

Runninng in the debugger we can see that `df` does not have the columns listed in  `season_cols`. There is some mistake here.

**Comment by marfcg** [comment]
This is due to the most recent changes in data input to incorporate gender into age distribution.
Now, the current_estimate csv no longer has age distribution, only the aggregate and opportunity estimations.
Age and gender details are in a separate file, without estimates.

More info can be found in the Notebook example.

**Comment by xmnlab** [comment]
After the new restructuration on the dataset, some functionaties do not
work anymore. So I create the unnittest to guide us. I'm working to resolve
these bugs. The first one was fixed in local env. The second one, that was
skiped in the PR, just for tests. Actually, I'm working to resolve charts
issue :(

**Comment by marfcg** [comment]
@xmnlab I'll PM you to check a few details regarding dataset. We might find a middle ground that makes things simpler.

**Comment by xmnlab** [comment]
I think the current problem is the chart .. i tried to test chartjs ... But
no success ... I'm trying to use mpld3 ... But have some problem when the
lib tries to dumps to json :S maybe some bug with numpy number.

**Comment by xmnlab** [comment]
I have found a way to plot categorical data bar chart with c3js:

https://jsfiddle.net/bm57gye5/

I'm working to release this today.

**Pull request merged**
